#!/bin/bash

# This script creates the configuration directory of a Mokamint node, for starting the first node
# of a newly initialized blockchain. The configuration directory will have the following structure:
#
# node.pem
# plot.plot
# mokamint_config.toml
#
# where:
# 1) node.pem is a key pair with empty password
# 2) plot.plot uses node.pem as key for signing the blocks, the provided public key as key for signing the deadlines and the provided chain identifier
# 3) options not explicitly reported in the toml configuration file hold, implicitly, default values

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

CHAIN_ID=${CHAIN_ID:-""}
PLOT_SIZE=${PLOT_SIZE:-1000}
PUBLIC_KEY_MINER_BASE58=${PUBLIC_KEY_MINER_BASE58:-""}
TARGET_BLOCK_CREATION_TIME=${TARGET_BLOCK_CREATION_TIME:-10000}

echo -e "${BOLD_GREEN}I will use the following parameters for the creation of the configuration directory of a proof of space Mokamint node:${NC}"
echo
echo -e "                    ${BLUE}CHAIN_ID${NC}=${RED}\"$CHAIN_ID\"${NC}"
echo -e "                   ${BLUE}PLOT_SIZE${NC}=${RED}$PLOT_SIZE${NC}"
echo -e "     ${BLUE}PUBLIC_KEY_MINER_BASE58${NC}=${RED}\"$PUBLIC_KEY_MINER_BASE58\"${NC}"
echo -e "  ${BLUE}TARGET_BLOCK_CREATION_TIME${NC}=${RED}$TARGET_BLOCK_CREATION_TIME${NC}"
echo

echo -n "Cleaning the directory mokamint... "
rm -rf mokamint/*
echo -e "${RED}done${NC}"

echo -n "Cleaning the directory chain... "
rm -rf chain/*
echo -e "${RED}done${NC}"

echo -n "Creating the node.pem key pair for signing the blocks: "
mokamint-node keys create --output-dir=mokamint --name=node.pem --password --json --redirection node_key_creation.json
PUBLIC_KEY_NODE_BASE58=$(cat node_key_creation.json | python3 -c "import sys, json; print(json.load(sys.stdin)['publicKeyBase58'])")
rm node_key_creation.json
chmod og-rwx mokamint/node.pem
echo -e "${RED}done:${NC} the public key is ${BOLD_GREEN}${PUBLIC_KEY_NODE_BASE58}${NC} (ed25519, base58)"

echo -n "Creating the Mokamint configuration file... "
echo "dir = \"chain\"" > mokamint/mokamint_config.toml
echo "chain_id = \"${CHAIN_ID}\"" >> mokamint/mokamint_config.toml
echo "target_block_creation_time = ${TARGET_BLOCK_CREATION_TIME}" >> mokamint/mokamint_config.toml
echo -e "${RED}done${NC}"

echo "Creating a plot file for the miner, containing ${PLOT_SIZE} nonces, for the chain id \"${CHAIN_ID}\", for a node with public key ${PUBLIC_KEY_NODE_BASE58} (ed25519, base58), for a miner with public key ${PUBLIC_KEY_MINER_BASE58} (ed25519, base58)..."
mokamint-plotter create mokamint/plot.plot 0 $PLOT_SIZE "$CHAIN_ID" $PUBLIC_KEY_NODE_BASE58 $PUBLIC_KEY_MINER_BASE58
echo -e "${RED}done${NC}"