#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
BOLD_CYAN='\033[1;36m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}This container provides the Mokamint tools:${NC}"
echo -e "* ${RED}mokamint-application:${NC} a manager of Mokamint applications"
echo -e "* ${RED}mokamint-miner:${NC}       a manager of Mokamint miners"
echo -e "* ${RED}mokamint-node:${NC}        a manager of Mokamint nodes"
echo -e "* ${RED}mokamint-plotter:${NC}     a manager of Mokamint plot files"
echo
echo -e "${BOLD_GREEN}Moreover, the following commands and options are available inside this container:${NC}"
echo -e "* ${RED}info:${NC}         print this information message"
echo
echo -e "* ${RED}config-miner:${NC} create the configuration directory of a miner service connected to a remote miner"
echo -e "    ${BLUE}MINER_PUBLIC_SERVICE_URI:${NC} the URI of an already existing remote miner"
echo -e "    ${BLUE}PUBLIC_KEY_MINER_BASE58:${NC} the Base58-encoded public key to use to identify the miner service"
echo -e "    ${BLUE}PLOT_SIZE:${NC} the number of nonces of the plot that the miner will use for mining"
echo -e "    ${BLUE}EXTRA:${NC} base58-encoded extra data to put in the nonces of the plot"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -it -e MINER_PUBLIC_SERVICE_URI=ws://lipari.hotmoka.io:8025 -e PUBLIC_KEY_MINER_BASE58=E4hbKgLjoen1sRNRmyPC59jgkjifCCUxjmGCAPnnSwvQ -v mokamint:/home/mokamint/mokamint mokamint/mokamint:VERSION config-miner${NC}"
echo
echo -e "* ${RED}mine:${NC}         create a mining service for a remote miner, whose configuration has been created with config-miner"
echo -e "    ${BLUE}MINER_PUBLIC_SERVICE_URI:${NC} the URI of an already existing remote miner"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run --log-driver local -it -e MINER_PUBLIC_SERVICE_URI=ws://lipari.hotmoka.io:8025 -v mokamint:/home/mokamint/mokamint mokamint/mokamint:VERSION mine${NC}"
echo
echo -e "* ${RED}config-new:${NC}   create the configuration directory of the first node of a brand new blockchain, with a local miner"
echo -e "    ${BLUE}ALLOWS_REPEATED_REQUESTS:${NC} true if and only if the blockchain must allow repeated identical requests"
echo -e "    ${BLUE}CHAIN_ID:${NC} the chain identifier of the blockchain"
echo -e "    ${BLUE}PLOT_SIZE:${NC} the number of nonces of the plot that the node will use for mining"
echo -e "    ${BLUE}PUBLIC_KEY_MINER_BASE58:${NC} the Base58-encoded public key that will identify the miner in the blockchain"
echo -e "    ${BLUE}TARGET_BLOCK_CREATION_TIME:${NC} the milliseconds between two successive blocks (on average)"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -it -e PUBLIC_KEY_MINER_BASE58=E4hbKgLjoen1sRNRmyPC59jgkjifCCUxjmGCAPnnSwvQ -v chain:/home/mokamint/chain -v mokamint:/home/mokamint/mokamint mokamint/mokamint:VERSION config-new${NC}"
echo
echo -e "* ${RED}config-clone:${NC} create the configuration directory of a new node of an existing blockchain, with a local miner"
echo -e "    ${BLUE}MOKAMINT_PUBLIC_SERVICE_URI:${NC} the URI of an already existing node of the blockchain"
echo -e "    ${BLUE}PLOT_SIZE:${NC} the number of nonces of the plot that the node will use for mining"
echo -e "    ${BLUE}PUBLIC_KEY_MINER_BASE58:${NC} the Base58-encoded public key that will identify the miner in the blockchain"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -it -e MOKAMINT_PUBLIC_SERVICE_URI=ws://....cloned url...:8030 -e PUBLIC_KEY_MINER_BASE58=E4hbKgLjoen1sRNRmyPC59jgkjifCCUxjmGCAPnnSwvQ -v chain:/home/mokamint/chain -v mokamint:/home/mokamint/mokamint mokamint/mokamint:VERSION config-clone${NC}"
echo
echo -e "* ${RED}init:${NC}         initialize a node for a brand new blockchain, whose configuration has been created with config-new"
echo -e "    ${BLUE}APPLICATION:${NC} the name of the application to run on top of Mokamint"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run -it -e APPLICATION=Parity -v chain:/home/mokamint/chain -v mokamint:/home/mokamint/mokamint mokamint/mokamint:VERSION init${NC}"
echo
echo -e "* ${RED}go:${NC}           start a node of a blockchain, whose configuration has been created with config-clone or with config-new and then init"
echo -e "    ${BLUE}APPLICATION:${NC} the name of the application to run on top of Mokamint"
echo -e "    ${BLUE}VISIBLE_AS:${NC} a URI that the external world can use to contact the new node"
echo
echo "  For instance:"
echo -e "  ${BOLD_CYAN}docker run --log-driver local -dit -e APPLICATION=Parity -p 8025:8025 -p 8030:8030 -p 8031:8031 -v chain:/home/mokamint/chain -v mokamint:/home/mokamint/mokamint mokamint/mokamint:VERSION go${NC}"
