#!/bin/bash

RED='\033[0;31m'
BOLD_GREEN='\033[1;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BOLD_GREEN}Starting a mining service for a remote miner.${NC}"
echo -e "${BLUE}MINER_PUBLIC_SERVICE_URI${NC}=${RED}\"$MINER_PUBLIC_SERVICE_URI\"${NC}"

mokamint-miner-print-logs start miner_configuration/plot.plot --uri ${MINER_PUBLIC_SERVICE_URI}
