#!/bin/bash

# this script runs the mokamint-node command-line tool of Mokamint

# let us determine the directory where this script is defined
# see https://stackoverflow.com/questions/59895/how-can-i-get-the-source-directory-of-a-bash-script-from-within-the-script-itsel

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"

DIR=$DIR"/.."

java --add-modules org.glassfish.tyrus.container.grizzly.server --module-path $DIR/modules/explicit:$DIR/modules/automatic --class-path $DIR"/modules/unnamed/*" --module io.mokamint.node.cli/io.mokamint.node.cli.MokamintNode "$@"
