# This is a TOML config file for Mokamint nodes.
# For more information about TOML, see https://github.com/toml-lang/toml
# For more information about Mokamint, see https://www.mokamint.io

## Consensus parameters

# the hashing algorithm used for the deadlines and hence for the plot files of the miners
hashing_for_deadlines = "shabal256"

# the hashing algorithm used for the computation of the new generation and scoop number from the previous block
hashing_for_generations = "sha256"

# the hashing algorithm used for the blocks of the blockchain
hashing_for_blocks = "sha256"

# time, in milliseconds, aimed between the creation of a block and the creation of a next block
target_block_creation_time = 240000

## Local parameters

# the path where the node's data will be persisted
dir = "mokamint-chain"

# maximal milliseconds to wait between deadline request to the miners and first deadline reception
deadline_wait_timeout = 20000

# the initial points of a miner, freshly connected to a node
miner_initial_points = 1000

# the points that a miner loses as punishment for a timeout at a request for a deadline
miner_punishment_for_timeout = 1

# the points that a miner loses as punishment for providing an illegal deadline
miner_punishment_for_illegal_deadline = 500

# the URIs of the initial peers, that will always get added to the previous set of peers
# (if any) and contacted at start-up
seeds = ["ws://mymachine.com:8026","ws://hermachine.de:8028"]

# the maximum amount of peers of a node; their actual number can be larger
# only if peers are explicitly added as seeds or through the addPeer() method
# of the restricted API of the node
max_peers = 20

# the initial points of a peer, freshly added to a node
peer_initial_points = 1000

# the points that a peer loses as punishment for not answering a ping
peer_punishment_for_unreachable = 1

# the time (in milliseconds) for communications to the peers
peer_timeout = 10000
